
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action newAction;

	private global::Gtk.Action openAction;

	private global::Gtk.Action saveAction;

	private global::Gtk.Action saveAsAction;

	private global::Gtk.Action quitAction;

	private global::Gtk.VBox vbox3;

	private global::Gtk.MenuBar menubar1;

	private global::Gtk.Frame frame1;

	private global::Gtk.Alignment GtkAlignment;

	private global::Gtk.Entry passwordBox;

	private global::Gtk.Label GtkLabel1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.VBox vbox1;

	private global::Gtk.VButtonBox vbuttonbox1;

	private global::Gtk.Button btnRemove1;

	private global::Gtk.Button btnAdd;

	private global::Gtk.Entry txtSearch;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TreeView treeview1;

	private global::Gtk.VBox vbox2;

	private global::Gtk.Frame frame2;

	private global::Gtk.Alignment GtkAlignment3;

	private global::Gtk.Entry txtTitle;

	private global::Gtk.Label GtkLabel4;

	private global::Gtk.Frame frame3;

	private global::Gtk.Alignment GtkAlignment4;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TextView txtContent;

	private global::Gtk.Label GtkLabel5;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
		w1.Add(this.FileAction, null);
		this.newAction = new global::Gtk.Action("newAction", global::Mono.Unix.Catalog.GetString("New"), null, "gtk-new");
		this.newAction.ShortLabel = global::Mono.Unix.Catalog.GetString("New");
		w1.Add(this.newAction, null);
		this.openAction = new global::Gtk.Action("openAction", global::Mono.Unix.Catalog.GetString("Open"), null, "gtk-open");
		this.openAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Open");
		w1.Add(this.openAction, null);
		this.saveAction = new global::Gtk.Action("saveAction", global::Mono.Unix.Catalog.GetString("Save"), null, "gtk-save");
		this.saveAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Save");
		w1.Add(this.saveAction, null);
		this.saveAsAction = new global::Gtk.Action("saveAsAction", global::Mono.Unix.Catalog.GetString("Save _As"), null, "gtk-save-as");
		this.saveAsAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Save _As");
		w1.Add(this.saveAsAction, null);
		this.quitAction = new global::Gtk.Action("quitAction", global::Mono.Unix.Catalog.GetString("Exit"), null, "gtk-quit");
		this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Exit");
		w1.Add(this.quitAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("CloudWallet GTK");
		this.Icon = global::Gdk.Pixbuf.LoadFromResource("CloudWallet_GTK.cloudWallet_256x256.ico");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString(@"<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='newAction' action='newAction'/><menuitem name='openAction' action='openAction'/><menuitem name='saveAction' action='saveAction'/><menuitem name='saveAsAction' action='saveAsAction'/><menuitem name='quitAction' action='quitAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox3.Add(this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		this.frame1.LabelXalign = 0.5F;
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.passwordBox = new global::Gtk.Entry();
		this.passwordBox.CanFocus = true;
		this.passwordBox.Name = "passwordBox";
		this.passwordBox.IsEditable = true;
		this.passwordBox.Visibility = false;
		this.passwordBox.InvisibleChar = '•';
		this.GtkAlignment.Add(this.passwordBox);
		this.frame1.Add(this.GtkAlignment);
		this.GtkLabel1 = new global::Gtk.Label();
		this.GtkLabel1.Name = "GtkLabel1";
		this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Password</b>");
		this.GtkLabel1.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel1;
		this.vbox3.Add(this.frame1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.frame1]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.WidthRequest = 300;
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbuttonbox1 = new global::Gtk.VButtonBox();
		this.vbuttonbox1.Name = "vbuttonbox1";
		// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.btnRemove1 = new global::Gtk.Button();
		this.btnRemove1.WidthRequest = 300;
		this.btnRemove1.CanFocus = true;
		this.btnRemove1.Name = "btnRemove1";
		this.btnRemove1.UseStock = true;
		this.btnRemove1.UseUnderline = true;
		this.btnRemove1.Label = "gtk-remove";
		this.vbuttonbox1.Add(this.btnRemove1);
		global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.btnRemove1]));
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.btnAdd = new global::Gtk.Button();
		this.btnAdd.WidthRequest = 300;
		this.btnAdd.CanFocus = true;
		this.btnAdd.Name = "btnAdd";
		this.btnAdd.UseStock = true;
		this.btnAdd.UseUnderline = true;
		this.btnAdd.Label = "gtk-add";
		this.vbuttonbox1.Add(this.btnAdd);
		global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.btnAdd]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		this.vbox1.Add(this.vbuttonbox1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbuttonbox1]));
		w8.Position = 0;
		w8.Expand = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.txtSearch = new global::Gtk.Entry();
		this.txtSearch.WidthRequest = 300;
		this.txtSearch.CanFocus = true;
		this.txtSearch.Name = "txtSearch";
		this.txtSearch.IsEditable = true;
		this.txtSearch.InvisibleChar = '•';
		this.vbox1.Add(this.txtSearch);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.txtSearch]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.treeview1 = new global::Gtk.TreeView();
		this.treeview1.WidthRequest = 300;
		this.treeview1.CanFocus = true;
		this.treeview1.Name = "treeview1";
		this.GtkScrolledWindow.Add(this.treeview1);
		this.vbox1.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
		w11.Position = 2;
		this.hbox1.Add(this.vbox1);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox1]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.frame2 = new global::Gtk.Frame();
		this.frame2.Name = "frame2";
		this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame2.Gtk.Container+ContainerChild
		this.GtkAlignment3 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment3.Name = "GtkAlignment3";
		this.GtkAlignment3.LeftPadding = ((uint)(12));
		// Container child GtkAlignment3.Gtk.Container+ContainerChild
		this.txtTitle = new global::Gtk.Entry();
		this.txtTitle.WidthRequest = 500;
		this.txtTitle.CanFocus = true;
		this.txtTitle.Name = "txtTitle";
		this.txtTitle.IsEditable = true;
		this.txtTitle.InvisibleChar = '•';
		this.GtkAlignment3.Add(this.txtTitle);
		this.frame2.Add(this.GtkAlignment3);
		this.GtkLabel4 = new global::Gtk.Label();
		this.GtkLabel4.Name = "GtkLabel4";
		this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Title</b>");
		this.GtkLabel4.UseMarkup = true;
		this.GtkLabel4.Justify = ((global::Gtk.Justification)(2));
		this.frame2.LabelWidget = this.GtkLabel4;
		this.vbox2.Add(this.frame2);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.frame2]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.frame3 = new global::Gtk.Frame();
		this.frame3.Name = "frame3";
		this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame3.Gtk.Container+ContainerChild
		this.GtkAlignment4 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment4.Name = "GtkAlignment4";
		this.GtkAlignment4.LeftPadding = ((uint)(12));
		// Container child GtkAlignment4.Gtk.Container+ContainerChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.txtContent = new global::Gtk.TextView();
		this.txtContent.CanFocus = true;
		this.txtContent.Name = "txtContent";
		this.GtkScrolledWindow1.Add(this.txtContent);
		this.GtkAlignment4.Add(this.GtkScrolledWindow1);
		this.frame3.Add(this.GtkAlignment4);
		this.GtkLabel5 = new global::Gtk.Label();
		this.GtkLabel5.Name = "GtkLabel5";
		this.GtkLabel5.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Content</b>");
		this.GtkLabel5.UseMarkup = true;
		this.frame3.LabelWidget = this.GtkLabel5;
		this.vbox2.Add(this.frame3);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.frame3]));
		w19.Position = 1;
		this.hbox1.Add(this.vbox2);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		this.vbox3.Add(this.hbox1);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox1]));
		w21.Position = 2;
		this.Add(this.vbox3);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 820;
		this.DefaultHeight = 469;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.newAction.Activated += new global::System.EventHandler(this.onFileNew);
		this.openAction.Activated += new global::System.EventHandler(this.onFileOpen);
		this.saveAction.Activated += new global::System.EventHandler(this.OnFileSave);
		this.saveAsAction.Activated += new global::System.EventHandler(this.onFileSaveAs);
		this.quitAction.Activated += new global::System.EventHandler(this.onFileExit);
		this.btnRemove1.Clicked += new global::System.EventHandler(this.btnRemove_Clicked);
		this.btnAdd.Clicked += new global::System.EventHandler(this.btnAdd_Clicked);
		this.txtSearch.Changed += new global::System.EventHandler(this.txtSearchChanged);
		this.treeview1.SelectCursorParent += new global::Gtk.SelectCursorParentHandler(this.treeview_selectCursuorParent);
		this.treeview1.SelectionReceived += new global::Gtk.SelectionReceivedHandler(this.tree_selectionrecieved);
		this.treeview1.CursorChanged += new global::System.EventHandler(this.tree_CursorChanged);
		this.txtTitle.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler(this.txtTitle_keyrelease);
		this.txtContent.InsertAtCursor += new global::Gtk.InsertAtCursorHandler(this.OnContentInsert);
		this.txtContent.DeleteFromCursor += new global::Gtk.DeleteFromCursorHandler(this.OnContentDelete);
		this.txtContent.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler(this.content_keyup);
	}
}
